version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'exampledb'
      MYSQL_USER: 'hyunwoo'
      MYSQL_PASSWORD: 'hyunwoo'
      MYSQL_ROOT_PASSWORD: 'hyunwoo'
    ports:
      - '3306:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'
volumes:
  mysqldata: